<%@ page contentType="text/html; charset=UTF-8"%>
<link href="${ctx}/common/ext/resources/css/ext-all.css" type="text/css" rel="stylesheet" />
<script src="${ctx}/common/ext/adapter/ext/ext-base.js" type="text/javascript"></script>
<script src="${ctx}/common/ext/ext-all.js" type="text/javascript"></script>
<script src="${ctx}/common/ext/ext-portal.js" type="text/javascript"></script>
<script type="text/javascript" src="${ctx}/common/ext/dialog/coral-popwin.js"></script>
<script type="text/javascript">
	Ext.BLANK_IMAGE_URL = '${pageContext.request.contextPath}/common/ext/resources/images/default/s.gif';
	Ext.MessageBox.buttonText.ok ="确定";
	Ext.MessageBox.buttonText.cancel ="取消";
	Ext.MessageBox.buttonText.yes ="是";
	Ext.MessageBox.buttonText.no ="否";
</script>

