<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<meta http-equiv="Cache-Control" content="no-store"/>
<meta http-equiv="Pragma" content="no-cache"/>
<meta http-equiv="Expires" content="0"/>
<base target="_self">
<script type="text/javascript">
var IMG_ACTIONS_PATH = '${ctx}/images/icon/CrystalClear/16/actions/';
var IMG_STATUS_PATH = '${ctx}/images/icon/CrystalClear/16/status/';
</script>