<%@ page contentType="text/html; charset=UTF-8"%>
<link rel="shortcut icon" href="${ctx}/favicon.ico" />
<link href="${ctx}/style/default.css" rel="stylesheet" type="text/css" rel="stylesheet">
<link href="${ctx}/common/ext/resources/css/ext-all.css" type="text/css" rel="stylesheet" />
<script type="text/javascript">
var CONTEXT_PATH = '${ctx}';
/*
document.onclick = function(o){
	if(window.top.resetTime){
		window.top.resetTime();
	}
}
*/
</script>