<%@ page contentType="text/html; charset=UTF-8"%>
<link href="${ctx}/common/tree/codebase/dhtmlxtree.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="${ctx}/common/tree/codebase/dhtmlxcommon.js"></script>
<script type="text/javascript" src="${ctx}/common/tree/codebase/dhtmlxtree.js"></script>
<script type="text/javascript">
var dhtmlXTreeImPath="${ctx}/common/tree/codebase/imgs/csh_books/";
var dhx_globalImgPath="${ctx}/common/tree/codebase/imgs/csh_books/";
</script>