<%@ page contentType="text/html; charset=UTF-8"%>
<link href="${ctx}/common/tree_1/css/dhtmlXTree.css" rel="stylesheet" type="text/css">
<script src="${ctx}/dwr/engine.js" type="text/javascript"></script>
<script src="${ctx}/dwr/util.js" type="text/javascript"></script>
<script type="text/javascript" src="${ctx}/common/tree_1/js/dhtmlXCommon.js"></script>
<script type="text/javascript" src="${ctx}/common/tree_1/js/dhtmlXTree.js"></script>
<script type="text/javascript">
var dhtmlXTreeImPath="${ctx}/common/tree_1/imgs/csh_books/";
</script>
<style type="text/css">
#application-tree{text-align: left;}
</style>